# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWhUg4QA6QqMpuHjl3YfzXsW_01brxZK
"""

#W2A1
print ("Hello World ")

#W2A2
user_name = input("Hi, what is your name? ")
print(f"Hello, {user_name}")

def add_numbers(a, b):
  result = a**b
  return result
  print(result)

p#W2A10
user_1 = input()
user_2 = input()
User_3 = input()
print(f"Hello {User_3}, {user_2} and {user_1}")

#W2A10
a, b, c = input().split()
print(f"Hi {c} ,  {b} and {a}")

#W2A16
print("Spring\nSummer\nAutumn\nWinter")

#W2A17
print("*")
print("***")
print("*****")

#W2A17
for i in range(1,6,2):
    print("*"*(i))

#W2A18
print("### # #  ### ###")
print(" #  #  #  #   #")
print(" #  #  #  #   #")
print(" #  # #   #   #")

#W2A19
print("Monday\nTuesday\nWednesday\nThursday\nFriday\nSaturday\nSunday")

#W2A20
print("January\nFebruary\nMarch\nApril\nMay\nJune\nJuly\nAugust\nSeptember\nOctober\nNovember\nDecember")

#W2A20
months = ["January","February","March","April","May","June","July","August","September","October","November","December"]
for i in range(12):
    print(months[i])

#W2A21
for i in range(10):
    print("Hello World")